name: Metrics
on:
  # Atualiza as 00:00 todos os dias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente na aba Actions
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token é gerado automaticamente pela action, não precisa criar secret
          token: ${{ secrets.GITHUB_TOKEN }}

          # Configurações Visuais
          user: SEU_USUARIO
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          
          # Plugin: Linguagens (detalhado)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: bytes-size, percentage
          
          # Plugin: Linhas de código (mostra que você "codapara valer")
          plugin_lines: yes
          
          # Plugin: Stack Overflow (opcional, se usar)
          # plugin_stackoverflow: yes
          # plugin_stackoverflow_user: SEU_ID_STACKOVERFLOW
